// Users
export const CREATE_USERS = "CREATE_USERS";
export const CREATE_USERS_RED = "CREATE_USERS_RED";
export const GET_USERS = "GET_USERS";
export const GET_USERS_RED = "GET_USERS_RED";
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USERS_RED = "UPDATE_USERS_RED";
export const DELETE_USERS = "DELETE_USERS";
export const DELETE_USERS_RED = "DELETE_USERS_RED";

// Feedback
export const CREATE_FEEDBACK = "CREATE_FEEDBACK";
export const CREATE_FEEDBACK_RED = "CREATE_FEEDBACK_RED";
export const GET_FEEDBACK = "GET_FEEDBACK";
export const GET_FEEDBACK_RED = "GET_FEEDBACK_RED";
export const UPDATE_FEEDBACK = "UPDATE_FEEDBACK";
export const UPDATE_FEEDBACK_RED = "UPDATE_FEEDBACK_RED";
export const DELETE_FEEDBACK = "DELETE_FEEDBACK";
export const DELETE_FEEDBACK_RED = "DELETE_FEEDBACK_RED";

// Appointments
export const CREATE_APPOINTMENTS = "CREATE_APPOINTMENTS";
export const CREATE_APPOINTMENTS_RED = "CREATE_APPOINTMENTS_RED";
export const GET_APPOINTMENTS = "GET_APPOINTMENTS";
export const GET_APPOINTMENTS_RED = "GET_APPOINTMENTS_RED";
export const UPDATE_APPOINTMENTS = "UPDATE_APPOINTMENTS";
export const UPDATE_APPOINTMENTS_RED = "UPDATE_APPOINTMENTS_RED";
export const DELETE_APPOINTMENTS = "DELETE_APPOINTMENTS";
export const DELETE_APPOINTMENTS_RED = "DELETE_APPOINTMENTS_RED";

// Advices
export const CREATE_ADVICES = "CREATE_ADVICES";
export const CREATE_ADVICES_RED = "CREATE_ADVICES_RED";
export const GET_ADVICES = "GET_ADVICES";
export const GET_ADVICES_RED = "GET_ADVICES_RED";
export const UPDATE_ADVICES = "UPDATE_ADVICES";
export const UPDATE_ADVICES_RED = "UPDATE_ADVICES_RED";
export const DELETE_ADVICES = "DELETE_ADVICES";
export const DELETE_ADVICES_RED = "DELETE_ADVICES_RED";
